//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.4.0.0 (NJsonSchema v11.3.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

import axios, { AxiosError } from 'axios';
import type {
    AxiosInstance,
    AxiosRequestConfig,
    AxiosResponse,
    CancelToken,
} from 'axios';

export class Client {
    protected instance: AxiosInstance;
    protected baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined =
        undefined;

    constructor(baseUrl?: string, instance?: AxiosInstance) {
        this.instance = instance || axios.create();

        this.baseUrl = baseUrl ?? '';
    }

    /**
     * @return OK
     */
    roomAll(cancelToken?: CancelToken): Promise<RoomResponse[]> {
        let url_ = this.baseUrl + '/api/Room';
        url_ = url_.replace(/[?&]$/, '');

        let options_: AxiosRequestConfig = {
            method: 'GET',
            url: url_,
            headers: {
                Accept: 'text/plain',
            },
            cancelToken,
        };

        return this.instance
            .request(options_)
            .catch((_error: any) => {
                if (isAxiosError(_error) && _error.response) {
                    return _error.response;
                } else {
                    throw _error;
                }
            })
            .then((_response: AxiosResponse) => {
                return this.processRoomAll(_response);
            });
    }

    protected processRoomAll(response: AxiosResponse): Promise<RoomResponse[]> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === 'object') {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200 = _responseText;
            result200 = JSON.parse(resultData200);
            return Promise.resolve<RoomResponse[]>(result200);
        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException(
                'An unexpected server error occurred.',
                status,
                _responseText,
                _headers
            );
        }
        return Promise.resolve<RoomResponse[]>(null as any);
    }

    /**
     * @param body (optional)
     * @return Created
     */
    roomPOST(
        body: CreateRoomRequest | undefined,
        cancelToken?: CancelToken
    ): Promise<void> {
        let url_ = this.baseUrl + '/api/Room';
        url_ = url_.replace(/[?&]$/, '');

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: 'POST',
            url: url_,
            headers: {
                'Content-Type': 'application/json',
            },
            cancelToken,
        };

        return this.instance
            .request(options_)
            .catch((_error: any) => {
                if (isAxiosError(_error) && _error.response) {
                    return _error.response;
                } else {
                    throw _error;
                }
            })
            .then((_response: AxiosResponse) => {
                return this.processRoomPOST(_response);
            });
    }

    protected processRoomPOST(response: AxiosResponse): Promise<void> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === 'object') {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 201) {
            const _responseText = response.data;
            return Promise.resolve<void>(null as any);
        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException(
                'An unexpected server error occurred.',
                status,
                _responseText,
                _headers
            );
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    roomGET(id: number, cancelToken?: CancelToken): Promise<void> {
        let url_ = this.baseUrl + '/api/Room/{id}';
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace('{id}', encodeURIComponent('' + id));
        url_ = url_.replace(/[?&]$/, '');

        let options_: AxiosRequestConfig = {
            method: 'GET',
            url: url_,
            headers: {},
            cancelToken,
        };

        return this.instance
            .request(options_)
            .catch((_error: any) => {
                if (isAxiosError(_error) && _error.response) {
                    return _error.response;
                } else {
                    throw _error;
                }
            })
            .then((_response: AxiosResponse) => {
                return this.processRoomGET(_response);
            });
    }

    protected processRoomGET(response: AxiosResponse): Promise<void> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === 'object') {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            return Promise.resolve<void>(null as any);
        } else if (status === 404) {
            const _responseText = response.data;
            let result404: any = null;
            let resultData404 = _responseText;
            result404 = JSON.parse(resultData404);
            return throwException(
                'Not Found',
                status,
                _responseText,
                _headers,
                result404
            );
        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException(
                'An unexpected server error occurred.',
                status,
                _responseText,
                _headers
            );
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param body (optional)
     * @return OK
     */
    roomPUT(
        id: number,
        body: CreateRoomRequest | undefined,
        cancelToken?: CancelToken
    ): Promise<void> {
        let url_ = this.baseUrl + '/api/Room/{id}';
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace('{id}', encodeURIComponent('' + id));
        url_ = url_.replace(/[?&]$/, '');

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: 'PUT',
            url: url_,
            headers: {
                'Content-Type': 'application/json',
            },
            cancelToken,
        };

        return this.instance
            .request(options_)
            .catch((_error: any) => {
                if (isAxiosError(_error) && _error.response) {
                    return _error.response;
                } else {
                    throw _error;
                }
            })
            .then((_response: AxiosResponse) => {
                return this.processRoomPUT(_response);
            });
    }

    protected processRoomPUT(response: AxiosResponse): Promise<void> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === 'object') {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            return Promise.resolve<void>(null as any);
        } else if (status === 400) {
            const _responseText = response.data;
            let result400: any = null;
            let resultData400 = _responseText;
            result400 = JSON.parse(resultData400);
            return throwException(
                'Bad Request',
                status,
                _responseText,
                _headers,
                result400
            );
        } else if (status === 404) {
            const _responseText = response.data;
            let result404: any = null;
            let resultData404 = _responseText;
            result404 = JSON.parse(resultData404);
            return throwException(
                'Not Found',
                status,
                _responseText,
                _headers,
                result404
            );
        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException(
                'An unexpected server error occurred.',
                status,
                _responseText,
                _headers
            );
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return No Content
     */
    roomDELETE(id: number, cancelToken?: CancelToken): Promise<void> {
        let url_ = this.baseUrl + '/api/Room/{id}';
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace('{id}', encodeURIComponent('' + id));
        url_ = url_.replace(/[?&]$/, '');

        let options_: AxiosRequestConfig = {
            method: 'DELETE',
            url: url_,
            headers: {},
            cancelToken,
        };

        return this.instance
            .request(options_)
            .catch((_error: any) => {
                if (isAxiosError(_error) && _error.response) {
                    return _error.response;
                } else {
                    throw _error;
                }
            })
            .then((_response: AxiosResponse) => {
                return this.processRoomDELETE(_response);
            });
    }

    protected processRoomDELETE(response: AxiosResponse): Promise<void> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === 'object') {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 204) {
            const _responseText = response.data;
            return Promise.resolve<void>(null as any);
        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException(
                'An unexpected server error occurred.',
                status,
                _responseText,
                _headers
            );
        }
        return Promise.resolve<void>(null as any);
    }
}

export interface ActivityResponse {
    activityId?: number;
    name?: string | undefined;
    description?: string | undefined;
}

export interface AddressResponse {
    addressId?: number;
    addressName?: string | undefined;
    city?: string | undefined;
    region?: string | undefined;
    postalCode?: string | undefined;
    country?: string | undefined;
    phoneNumber?: string | undefined;
}

export interface CreateRoomRequest {
    name?: string | undefined;
    description?: string | undefined;
    pricePerHour?: number;
    isActive?: boolean;
    addressId?: number;
    address?: AddressResponse;
    activities?: ActivityResponse[] | undefined;
}

export interface ProblemDetails {
    type?: string | undefined;
    title?: string | undefined;
    status?: number | undefined;
    detail?: string | undefined;
    instance?: string | undefined;

    [key: string]: any;
}

export interface RoomResponse {
    roomId?: number;
    name?: string | undefined;
    description?: string | undefined;
    pricePerHour?: number;
    isActive?: boolean;
    address?: AddressResponse;
    activity?: ActivityResponse[] | undefined;
}

export class SwaggerException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any };
    result: any;

    constructor(
        message: string,
        status: number,
        response: string,
        headers: { [key: string]: any },
        result: any
    ) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isSwaggerException = true;

    static isSwaggerException(obj: any): obj is SwaggerException {
        return obj.isSwaggerException === true;
    }
}

function throwException(
    message: string,
    status: number,
    response: string,
    headers: { [key: string]: any },
    result?: any
): any {
    if (result !== null && result !== undefined) throw result;
    else throw new SwaggerException(message, status, response, headers, null);
}

function isAxiosError(obj: any): obj is AxiosError {
    return obj && obj.isAxiosError === true;
}
