// <auto-generated />
using LumeLaht_RoomApi.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LumeLaht_RoomApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250414013421_SeedDataToDb")]
    partial class SeedDataToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LumaCove_Api.Domain.Entities.Activity", b =>
                {
                    b.Property<int>("ActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActivityId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ActivityId");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            ActivityId = 1,
                            Description = "Table Game",
                            Name = "Monopolia"
                        },
                        new
                        {
                            ActivityId = 2,
                            Description = "Table Game",
                            Name = "Uno"
                        },
                        new
                        {
                            ActivityId = 3,
                            Description = "Table Game",
                            Name = "Chess"
                        },
                        new
                        {
                            ActivityId = 4,
                            Description = "Table Game",
                            Name = "Scrabble"
                        },
                        new
                        {
                            ActivityId = 5,
                            Description = "Sport Game",
                            Name = "Ping Pong"
                        },
                        new
                        {
                            ActivityId = 6,
                            Description = "Sport Game",
                            Name = "Foosball"
                        },
                        new
                        {
                            ActivityId = 7,
                            Description = "Sport Game",
                            Name = "Billiards"
                        },
                        new
                        {
                            ActivityId = 8,
                            Description = "Sport Game",
                            Name = "Darts"
                        },
                        new
                        {
                            ActivityId = 9,
                            Description = "Sport Game",
                            Name = "Poker"
                        },
                        new
                        {
                            ActivityId = 10,
                            Description = "Sport Game",
                            Name = "Blackjack"
                        },
                        new
                        {
                            ActivityId = 11,
                            Description = "Sport Game",
                            Name = "Bowling"
                        },
                        new
                        {
                            ActivityId = 12,
                            Description = "Sport Game",
                            Name = "Table Tennis"
                        });
                });

            modelBuilder.Entity("LumaCove_Api.Domain.Entities.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AddressId");

                    b.ToTable("Address");

                    b.HasData(
                        new
                        {
                            AddressId = 1,
                            City = "Narva",
                            Country = "Estonia",
                            PhoneNumber = "+37254356533",
                            PostalCode = "12341",
                            Region = "Ida-Virumaa"
                        },
                        new
                        {
                            AddressId = 2,
                            City = "Narva",
                            Country = "Estonia",
                            PhoneNumber = "+37254351534",
                            PostalCode = "12342",
                            Region = "Ida-Virumaa"
                        },
                        new
                        {
                            AddressId = 3,
                            City = "Jõhvi",
                            Country = "Estonia",
                            PhoneNumber = "+37254326535",
                            PostalCode = "12343",
                            Region = "Ida-Virumaa"
                        },
                        new
                        {
                            AddressId = 4,
                            City = "Narva",
                            Country = "Estonia",
                            PhoneNumber = "+37254365536",
                            PostalCode = "12344",
                            Region = "Ida-Virumaa"
                        },
                        new
                        {
                            AddressId = 5,
                            City = "Tallinn",
                            Country = "Estonia",
                            PhoneNumber = "+37254356537",
                            PostalCode = "12345",
                            Region = "Tallinn"
                        },
                        new
                        {
                            AddressId = 6,
                            City = "Tallinn",
                            Country = "Estonia",
                            PhoneNumber = "+37254356538",
                            PostalCode = "12346",
                            Region = "Tallinn"
                        });
                });

            modelBuilder.Entity("LumaCove_Api.Domain.Entities.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomId"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("PricePerHour")
                        .HasColumnType("float");

                    b.HasKey("RoomId");

                    b.HasIndex("AddressId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            RoomId = 1,
                            AddressId = 1,
                            Description = "Description A",
                            IsActive = true,
                            Name = "Room A",
                            PricePerHour = 25.5
                        },
                        new
                        {
                            RoomId = 2,
                            AddressId = 2,
                            Description = "Description B",
                            IsActive = true,
                            Name = "Room B",
                            PricePerHour = 30.0
                        },
                        new
                        {
                            RoomId = 3,
                            AddressId = 3,
                            Description = "Description C",
                            IsActive = true,
                            Name = "Room C",
                            PricePerHour = 35.0
                        },
                        new
                        {
                            RoomId = 4,
                            AddressId = 4,
                            Description = "Description D",
                            IsActive = true,
                            Name = "Room D",
                            PricePerHour = 40.0
                        },
                        new
                        {
                            RoomId = 5,
                            AddressId = 5,
                            Description = "Description E",
                            IsActive = true,
                            Name = "Room E",
                            PricePerHour = 45.0
                        },
                        new
                        {
                            RoomId = 6,
                            AddressId = 6,
                            Description = "Description F",
                            IsActive = true,
                            Name = "Room F",
                            PricePerHour = 50.0
                        });
                });

            modelBuilder.Entity("LumaCove_Api.Domain.Entities.RoomActivity", b =>
                {
                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.HasKey("RoomId", "ActivityId");

                    b.HasIndex("ActivityId");

                    b.ToTable("RoomsActivity");

                    b.HasData(
                        new
                        {
                            RoomId = 1,
                            ActivityId = 1
                        },
                        new
                        {
                            RoomId = 1,
                            ActivityId = 2
                        },
                        new
                        {
                            RoomId = 2,
                            ActivityId = 3
                        },
                        new
                        {
                            RoomId = 2,
                            ActivityId = 4
                        },
                        new
                        {
                            RoomId = 3,
                            ActivityId = 5
                        },
                        new
                        {
                            RoomId = 3,
                            ActivityId = 6
                        },
                        new
                        {
                            RoomId = 4,
                            ActivityId = 7
                        },
                        new
                        {
                            RoomId = 4,
                            ActivityId = 8
                        },
                        new
                        {
                            RoomId = 5,
                            ActivityId = 9
                        },
                        new
                        {
                            RoomId = 5,
                            ActivityId = 10
                        },
                        new
                        {
                            RoomId = 6,
                            ActivityId = 11
                        },
                        new
                        {
                            RoomId = 6,
                            ActivityId = 12
                        });
                });

            modelBuilder.Entity("LumaCove_Api.Domain.Entities.Room", b =>
                {
                    b.HasOne("LumaCove_Api.Domain.Entities.Address", "Address")
                        .WithMany("Rooms")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("LumaCove_Api.Domain.Entities.RoomActivity", b =>
                {
                    b.HasOne("LumaCove_Api.Domain.Entities.Activity", "Activity")
                        .WithMany("RoomActivity")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LumaCove_Api.Domain.Entities.Room", "Room")
                        .WithMany("RoomActivity")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("LumaCove_Api.Domain.Entities.Activity", b =>
                {
                    b.Navigation("RoomActivity");
                });

            modelBuilder.Entity("LumaCove_Api.Domain.Entities.Address", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("LumaCove_Api.Domain.Entities.Room", b =>
                {
                    b.Navigation("RoomActivity");
                });
#pragma warning restore 612, 618
        }
    }
}
