// <auto-generated />
using System;
using LumeLaht_RoomApi.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LumeLaht_RoomApi.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251210123314_BaseCreatedMigration")]
    partial class BaseCreatedMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LumeLaht_RoomApi.Core_.Entities.Activity", b =>
                {
                    b.Property<Guid>("ActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ActivityId");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            ActivityId = new Guid("43000001-0000-0000-0000-000000000000"),
                            Description = "Table Game",
                            Name = "Monopolia"
                        },
                        new
                        {
                            ActivityId = new Guid("43000002-0000-0000-0000-000000000000"),
                            Description = "Table Game",
                            Name = "Uno"
                        },
                        new
                        {
                            ActivityId = new Guid("43000003-0000-0000-0000-000000000000"),
                            Description = "Table Game",
                            Name = "Chess"
                        },
                        new
                        {
                            ActivityId = new Guid("43000004-0000-0000-0000-000000000000"),
                            Description = "Table Game",
                            Name = "Scrabble"
                        },
                        new
                        {
                            ActivityId = new Guid("43000005-0000-0000-0000-000000000000"),
                            Description = "Sport Game",
                            Name = "Ping Pong"
                        },
                        new
                        {
                            ActivityId = new Guid("43000006-0000-0000-0000-000000000000"),
                            Description = "Sport Game",
                            Name = "Foosball"
                        },
                        new
                        {
                            ActivityId = new Guid("43000007-0000-0000-0000-000000000000"),
                            Description = "Sport Game",
                            Name = "Billiards"
                        },
                        new
                        {
                            ActivityId = new Guid("43000008-0000-0000-0000-000000000000"),
                            Description = "Sport Game",
                            Name = "Darts"
                        },
                        new
                        {
                            ActivityId = new Guid("43000009-0000-0000-0000-000000000000"),
                            Description = "Sport Game",
                            Name = "Poker"
                        },
                        new
                        {
                            ActivityId = new Guid("43000010-0000-0000-0000-000000000000"),
                            Description = "Sport Game",
                            Name = "Blackjack"
                        },
                        new
                        {
                            ActivityId = new Guid("43000011-0000-0000-0000-000000000000"),
                            Description = "Sport Game",
                            Name = "Bowling"
                        },
                        new
                        {
                            ActivityId = new Guid("43000012-0000-0000-0000-000000000000"),
                            Description = "Sport Game",
                            Name = "Table Tennis"
                        });
                });

            modelBuilder.Entity("LumeLaht_RoomApi.Core_.Entities.Address", b =>
                {
                    b.Property<Guid>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AddressName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AddressId");

                    b.ToTable("Address");

                    b.HasData(
                        new
                        {
                            AddressId = new Guid("42000001-0000-0000-0000-000000000000"),
                            AddressName = "Gagarini 11",
                            City = "Narva",
                            Country = "Estonia",
                            PhoneNumber = "+37254356533",
                            PostalCode = "12341",
                            Region = "Ida-Virumaa"
                        },
                        new
                        {
                            AddressId = new Guid("42000002-0000-0000-0000-000000000000"),
                            AddressName = "Narva mnt 32",
                            City = "Narva",
                            Country = "Estonia",
                            PhoneNumber = "+37254351534",
                            PostalCode = "12342",
                            Region = "Ida-Virumaa"
                        },
                        new
                        {
                            AddressId = new Guid("42000003-0000-0000-0000-000000000000"),
                            AddressName = "Taamsaare 24",
                            City = "Jõhvi",
                            Country = "Estonia",
                            PhoneNumber = "+37254326535",
                            PostalCode = "12343",
                            Region = "Ida-Virumaa"
                        },
                        new
                        {
                            AddressId = new Guid("42000004-0000-0000-0000-000000000000"),
                            AddressName = "Vaba mnt 105",
                            City = "Narva",
                            Country = "Estonia",
                            PhoneNumber = "+37254365536",
                            PostalCode = "12344",
                            Region = "Ida-Virumaa"
                        },
                        new
                        {
                            AddressId = new Guid("42000005-0000-0000-0000-000000000000"),
                            AddressName = "Tallina mnt 25",
                            City = "Tallinn",
                            Country = "Estonia",
                            PhoneNumber = "+37254356537",
                            PostalCode = "12345",
                            Region = "Tallinn"
                        },
                        new
                        {
                            AddressId = new Guid("42000006-0000-0000-0000-000000000000"),
                            AddressName = "Tallina mnt 23",
                            City = "Tallinn",
                            Country = "Estonia",
                            PhoneNumber = "+37254356538",
                            PostalCode = "12346",
                            Region = "Tallinn"
                        });
                });

            modelBuilder.Entity("LumeLaht_RoomApi.Core_.Entities.Room", b =>
                {
                    b.Property<Guid>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PricePerHour")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoomId");

                    b.HasIndex("AddressId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            RoomId = new Guid("46000001-0000-0000-0000-000000000000"),
                            AddressId = new Guid("42000001-0000-0000-0000-000000000000"),
                            Description = "Description A",
                            Name = "Room A",
                            PricePerHour = 25.5m,
                            Status = "Available"
                        },
                        new
                        {
                            RoomId = new Guid("46000002-0000-0000-0000-000000000000"),
                            AddressId = new Guid("42000002-0000-0000-0000-000000000000"),
                            Description = "Description B",
                            Name = "Room B",
                            PricePerHour = 30m,
                            Status = "Available"
                        },
                        new
                        {
                            RoomId = new Guid("46000003-0000-0000-0000-000000000000"),
                            AddressId = new Guid("42000003-0000-0000-0000-000000000000"),
                            Description = "Description C",
                            Name = "Room C",
                            PricePerHour = 35m,
                            Status = "Available"
                        },
                        new
                        {
                            RoomId = new Guid("46000004-0000-0000-0000-000000000000"),
                            AddressId = new Guid("42000004-0000-0000-0000-000000000000"),
                            Description = "Description D",
                            Name = "Room D",
                            PricePerHour = 40m,
                            Status = "Maintenance"
                        },
                        new
                        {
                            RoomId = new Guid("46000005-0000-0000-0000-000000000000"),
                            AddressId = new Guid("42000005-0000-0000-0000-000000000000"),
                            Description = "Description E",
                            Name = "Room E",
                            PricePerHour = 45m,
                            Status = "Available"
                        },
                        new
                        {
                            RoomId = new Guid("46000006-0000-0000-0000-000000000000"),
                            AddressId = new Guid("42000006-0000-0000-0000-000000000000"),
                            Description = "Description F",
                            Name = "Room F",
                            PricePerHour = 50m,
                            Status = "Available"
                        });
                });

            modelBuilder.Entity("LumeLaht_RoomApi.Core_.Entities.RoomActivity", b =>
                {
                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RoomId", "ActivityId");

                    b.HasIndex("ActivityId");

                    b.ToTable("RoomsActivity");

                    b.HasData(
                        new
                        {
                            RoomId = new Guid("46000001-0000-0000-0000-000000000000"),
                            ActivityId = new Guid("43000001-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            RoomId = new Guid("46000001-0000-0000-0000-000000000000"),
                            ActivityId = new Guid("43000002-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            RoomId = new Guid("46000002-0000-0000-0000-000000000000"),
                            ActivityId = new Guid("43000003-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            RoomId = new Guid("46000002-0000-0000-0000-000000000000"),
                            ActivityId = new Guid("43000004-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            RoomId = new Guid("46000003-0000-0000-0000-000000000000"),
                            ActivityId = new Guid("43000005-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            RoomId = new Guid("46000003-0000-0000-0000-000000000000"),
                            ActivityId = new Guid("43000006-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            RoomId = new Guid("46000004-0000-0000-0000-000000000000"),
                            ActivityId = new Guid("43000007-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            RoomId = new Guid("46000004-0000-0000-0000-000000000000"),
                            ActivityId = new Guid("43000008-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            RoomId = new Guid("46000005-0000-0000-0000-000000000000"),
                            ActivityId = new Guid("43000009-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            RoomId = new Guid("46000005-0000-0000-0000-000000000000"),
                            ActivityId = new Guid("43000010-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            RoomId = new Guid("46000006-0000-0000-0000-000000000000"),
                            ActivityId = new Guid("43000011-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            RoomId = new Guid("46000006-0000-0000-0000-000000000000"),
                            ActivityId = new Guid("43000012-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("LumeLaht_RoomApi.Core_.Entities.RoomImage", b =>
                {
                    b.Property<Guid>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ImageId");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomImages");

                    b.HasData(
                        new
                        {
                            ImageId = new Guid("44000001-0000-0000-0000-000000000000"),
                            IsMain = true,
                            RoomId = new Guid("46000001-0000-0000-0000-000000000000"),
                            Url = "https://edef6.pcloud.com/DLZWFU6B6ZErvSOj7ZOjDfZZyHl10kZNVZZQYVZZn7M7ZzRZN4ZXLZaRIc8C2DvgjCj7EOMDkcnu0LrCFy/chairs-2181980_1920.jpg"
                        },
                        new
                        {
                            ImageId = new Guid("44000002-0000-0000-0000-000000000000"),
                            IsMain = true,
                            RoomId = new Guid("46000002-0000-0000-0000-000000000000"),
                            Url = "https://edef10.pcloud.com/cfZGzI1DZt6wfOj7ZOjDfZZTHl10kZNVZZQYVZZvRpCZwHZPZc7ZEHZoZQFZZx7Zp7Z7LZTVZe7ZWLZ4kZJ0xXJLg2QHRU1NeDLwgBCFGb5AY7/inter-er-restorana.jpg"
                        },
                        new
                        {
                            ImageId = new Guid("44000003-0000-0000-0000-000000000000"),
                            IsMain = true,
                            RoomId = new Guid("46000003-0000-0000-0000-000000000000"),
                            Url = "https://edef10.pcloud.com/cfZv1PIsZzxwfOj7ZOjDfZZwzl10kZNVZZQYVZZExBtZRXZ0RZcLZD7Zk5ZU7ZS7Z0zZL7ZTkZDVZ2Z3kZKFZSMQ4xFQQzF495zWLLGbSyHWUq2WV/inter-er-vystrel-iz-kafe-so-stul-ami-vozle-bara-s-derevannymi-stolami.jpg"
                        },
                        new
                        {
                            ImageId = new Guid("44000004-0000-0000-0000-000000000000"),
                            IsMain = true,
                            RoomId = new Guid("46000004-0000-0000-0000-000000000000"),
                            Url = "https://edef10.pcloud.com/DLZUTPOB6ZSgifOj7ZOjDfZZJRl10kZNVZZQYVZZvwBZCRZNRZT8ZeLyDsVPx5FhSJdO3T1lkfY2PaiwX/photo-1497366811353-6870744d04b2.jpg"
                        },
                        new
                        {
                            ImageId = new Guid("44000005-0000-0000-0000-000000000000"),
                            IsMain = true,
                            RoomId = new Guid("46000005-0000-0000-0000-000000000000"),
                            Url = "https://edef8.pcloud.com/DLZu0sOB6Zq6wfOj7ZOjDfZZPRl10kZNVZZQYVZZhOE7ZdLZi5ZE8Z7I5tNY0r9qVPGtCmfXBDPmca9Osk/vintage-aesthetic-7131604_1920.jpg"
                        },
                        new
                        {
                            ImageId = new Guid("44000006-0000-0000-0000-000000000000"),
                            IsMain = true,
                            RoomId = new Guid("46000006-0000-0000-0000-000000000000"),
                            Url = "https://edef4.pcloud.com/DLZzMPOB6ZjMifOj7ZOjDfZZrRl10kZNVZZQYVZZTUmZzJZg8ZA4Z2Ko1Jk2Ac8hX3jSG8WtmwkFK20v7/photo-1497366216548-37526070297c.jpg"
                        },
                        new
                        {
                            ImageId = new Guid("44000007-0000-0000-0000-000000000000"),
                            IsMain = false,
                            RoomId = new Guid("46000001-0000-0000-0000-000000000000"),
                            Url = "https://edef11.pcloud.com/DLZTTPOB6Z2gifOj7ZOjDfZZSLl10kZNVZZQYVZZ0DjZzzZH4Z44ZxUM7yrRl9X4uS0QPdocoem0EWnik/photo-1497366754035-f200968a6e72.jpg"
                        },
                        new
                        {
                            ImageId = new Guid("44000008-0000-0000-0000-000000000000"),
                            IsMain = false,
                            RoomId = new Guid("46000001-0000-0000-0000-000000000000"),
                            Url = "https://edef10.pcloud.com/DLZUTPOB6ZSgifOj7ZOjDfZZz4l10kZNVZZQYVZZvwBZCRZT8ZNRZuWuQtIxC4JyR37GkGAycnjp68Gfy/photo-1497366811353-6870744d04b2.jpg"
                        },
                        new
                        {
                            ImageId = new Guid("44000009-0000-0000-0000-000000000000"),
                            IsMain = false,
                            RoomId = new Guid("46000002-0000-0000-0000-000000000000"),
                            Url = "https://edef11.pcloud.com/DLZTTPOB6Z2gifOj7ZOjDfZZLsl10kZNVZZQYVZZ0DjZH4ZzzZ44ZqmYhXTdU6l5cOmHyJpPBe0tIXs7k/photo-1497366754035-f200968a6e72.jpg"
                        },
                        new
                        {
                            ImageId = new Guid("44000010-0000-0000-0000-000000000000"),
                            IsMain = false,
                            RoomId = new Guid("46000002-0000-0000-0000-000000000000"),
                            Url = "https://edef10.pcloud.com/DLZUTPOB6ZSgifOj7ZOjDfZZisl10kZNVZZQYVZZvwBZCRZT8ZNRZVIJlV2Lv1qQDm8LQHxofDBv02GDX/photo-1497366811353-6870744d04b2.jpg"
                        },
                        new
                        {
                            ImageId = new Guid("44000011-0000-0000-0000-000000000000"),
                            IsMain = false,
                            RoomId = new Guid("46000003-0000-0000-0000-000000000000"),
                            Url = "https://edef11.pcloud.com/DLZTTPOB6Z2gifOj7ZOjDfZZqDl10kZNVZZQYVZZ0DjZ44ZH4ZzzZEkzylnQCisBKyhTJUaMP6jxozogX/photo-1497366754035-f200968a6e72.jpg"
                        },
                        new
                        {
                            ImageId = new Guid("44000012-0000-0000-0000-000000000000"),
                            IsMain = false,
                            RoomId = new Guid("46000003-0000-0000-0000-000000000000"),
                            Url = "https://edef10.pcloud.com/DLZUTPOB6ZSgifOj7ZOjDfZZH1l10kZNVZZQYVZZvwBZCRZNRZT8Zbc0hNNc8KdjJFtTJ3hyUwp3xeAbX/photo-1497366811353-6870744d04b2.jpg"
                        },
                        new
                        {
                            ImageId = new Guid("44000013-0000-0000-0000-000000000000"),
                            IsMain = false,
                            RoomId = new Guid("46000004-0000-0000-0000-000000000000"),
                            Url = "https://edef11.pcloud.com/DLZTTPOB6Z2gifOj7ZOjDfZZC1l10kZNVZZQYVZZ0DjZH4Z44ZzzZ4df3TUten8yDWnGx26XlCmeS10yk/photo-1497366754035-f200968a6e72.jpg"
                        },
                        new
                        {
                            ImageId = new Guid("44000014-0000-0000-0000-000000000000"),
                            IsMain = false,
                            RoomId = new Guid("46000004-0000-0000-0000-000000000000"),
                            Url = "https://edef10.pcloud.com/DLZUTPOB6ZSgifOj7ZOjDfZZH1l10kZNVZZQYVZZvwBZCRZNRZT8Zbc0hNNc8KdjJFtTJ3hyUwp3xeAbX/photo-1497366811353-6870744d04b2.jpg"
                        },
                        new
                        {
                            ImageId = new Guid("44000015-0000-0000-0000-000000000000"),
                            IsMain = false,
                            RoomId = new Guid("46000005-0000-0000-0000-000000000000"),
                            Url = "https://edef11.pcloud.com/DLZTTPOB6Z2gifOj7ZOjDfZZC1l10kZNVZZQYVZZ0DjZH4Z44ZzzZ4df3TUten8yDWnGx26XlCmeS10yk/photo-1497366754035-f200968a6e72.jpg"
                        },
                        new
                        {
                            ImageId = new Guid("44000016-0000-0000-0000-000000000000"),
                            IsMain = false,
                            RoomId = new Guid("46000005-0000-0000-0000-000000000000"),
                            Url = "https://edef10.pcloud.com/DLZUTPOB6ZSgifOj7ZOjDfZZH1l10kZNVZZQYVZZvwBZCRZNRZT8Zbc0hNNc8KdjJFtTJ3hyUwp3xeAbX/photo-1497366811353-6870744d04b2.jpg"
                        },
                        new
                        {
                            ImageId = new Guid("44000017-0000-0000-0000-000000000000"),
                            IsMain = false,
                            RoomId = new Guid("46000006-0000-0000-0000-000000000000"),
                            Url = "https://edef11.pcloud.com/DLZTTPOB6Z2gifOj7ZOjDfZZC1l10kZNVZZQYVZZ0DjZH4Z44ZzzZ4df3TUten8yDWnGx26XlCmeS10yk/photo-1497366754035-f200968a6e72.jpg"
                        },
                        new
                        {
                            ImageId = new Guid("44000018-0000-0000-0000-000000000000"),
                            IsMain = false,
                            RoomId = new Guid("46000006-0000-0000-0000-000000000000"),
                            Url = "https://edef10.pcloud.com/DLZUTPOB6ZSgifOj7ZOjDfZZH1l10kZNVZZQYVZZvwBZCRZNRZT8Zbc0hNNc8KdjJFtTJ3hyUwp3xeAbX/photo-1497366811353-6870744d04b2.jpg"
                        });
                });

            modelBuilder.Entity("LumeLaht_RoomApi.Core_.Entities.Room", b =>
                {
                    b.HasOne("LumeLaht_RoomApi.Core_.Entities.Address", "Address")
                        .WithMany("Rooms")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("LumeLaht_RoomApi.Core_.Entities.RoomActivity", b =>
                {
                    b.HasOne("LumeLaht_RoomApi.Core_.Entities.Activity", "Activity")
                        .WithMany("RoomActivity")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LumeLaht_RoomApi.Core_.Entities.Room", "Room")
                        .WithMany("RoomActivity")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("LumeLaht_RoomApi.Core_.Entities.RoomImage", b =>
                {
                    b.HasOne("LumeLaht_RoomApi.Core_.Entities.Room", "Room")
                        .WithMany("Images")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("LumeLaht_RoomApi.Core_.Entities.Activity", b =>
                {
                    b.Navigation("RoomActivity");
                });

            modelBuilder.Entity("LumeLaht_RoomApi.Core_.Entities.Address", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("LumeLaht_RoomApi.Core_.Entities.Room", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("RoomActivity");
                });
#pragma warning restore 612, 618
        }
    }
}
